# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-10 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('matric_no', models.CharField(max_length=50, unique=True)),
                ('session', models.CharField(blank=True, choices=[('', 'Select Year'), ('2018/2019', '2018/2019'), ('2019/2020', '2019/2020')], max_length=50)),
                ('College', models.CharField(blank=True, choices=[('', 'Select College'), ('COLLEGE OF SCIENCE', 'Science'), ('COLLEGE OF TECHNOLOGY', 'Technology')], max_length=50, null=True)),
                ('level', models.CharField(blank=True, choices=[('', 'Select Level'), ('300', '300'), ('400', '400')], max_length=50, null=True)),
                ('department', models.CharField(blank=True, choices=[('', 'Select Dept'), ('Chemistry', 'Chemistry'), ('Industrial Chemistry', 'Industrial Chemistry'), ('Physics', 'Physics'), ('Geophysics', 'Geophysics'), ('Geology', 'Geology'), ('Computer Science', 'Computer Science'), ('Mathematics', 'Mathematics'), ('Environmental Management Toxicology', 'Environmental Sci'), ('Petroleum Engineering', 'Petroleum Eng'), ('Chemical Engineering', 'Chemical Eng'), ('Electrical Electronics Engineering', 'Electrical Eng'), ('Mechanical Engineering', 'Mechanical Eng'), ('Marine Engineering', 'Marine Eng')], max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewzUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('by', models.CharField(blank=True, default='Admin', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiwesInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('accountNo', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('sort_code', models.CharField(blank=True, max_length=50, null=True)),
                ('phoneNo', models.CharField(blank=True, max_length=50, null=True)),
                ('industryName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('industryAddress', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('industrySupervisorname', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('industrySupervisorPhoneno', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisorName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('supervisorPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisorDept', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisorEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
