# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-11 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newzupdate',
            name='by',
            field=models.CharField(blank=True, default='Admin', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('', 'Select Dept'), ('Chemistry', 'Chemistry'), ('Industrial Chemistry', 'Industrial Chemistry'), ('Physics', 'Physics'), ('Geophysics', 'Geophysics'), ('Geology', 'Geology'), ('Computer Science', 'Computer Science'), ('Mathematics', 'Mathematics'), ('Environmental Management Toxicology', 'Environmental Sci'), ('Petroleum Engineering', 'Petroleum Engr'), ('Chemical Engineering', 'Chemical Engr'), ('Electrical Electronics Engineering', 'Elect/Elect Engr'), ('Mechanical Engineering', 'Mechanical Engr'), ('Marine Engineering', 'Marine Engr')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='session',
            field=models.CharField(blank=True, choices=[('', 'Select Year'), ('2018/2019', '2018/2019')], max_length=50),
        ),
    ]
