# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-11-21 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190511_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='newzupdate',
            name='file',
            field=models.FileField(null=True, upload_to='docs'),
        ),
    ]
